name: pos
description: "Aplikasi POS UMKM - Point of Sale untuk Usaha Mikro, Kecil, dan Menengah"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6

  # Database
  sqflite: ^2.3.0
  sqflite_sqlcipher: ^3.2.0
  path: ^1.8.3

  # Network & API
  dio: ^5.4.0
  connectivity_plus: ^5.0.2

  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  get_storage: ^2.1.1

  # UI Components
  cupertino_icons: ^1.0.8
  flutter_slidable: ^3.0.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  fl_chart: ^0.66.0

  # Utils
  intl: ^0.19.0
  uuid: ^4.2.1
  logger: ^2.0.2+1
  permission_handler: ^11.1.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  
  # Internationalization
  flutter_localizations:
    sdk: flutter

  # Hardware Integration
  blue_thermal_printer: ^1.2.0
  flutter_barcode_scanner: ^2.0.0
  image_picker: ^1.0.4
  camera: ^0.10.5+5

  # PDF & Export
  pdf: ^3.10.7
  printing: ^5.11.1

  # ML/AI
  tflite_flutter: ^0.10.4

  # Other
  url_launcher: ^6.2.2
  device_info_plus: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  
  # Internationalization
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/models/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
